version: 2.1

jobs:
  test-db:
    docker:
      - image: circleci/python:latest
      - image: circleci/mongo:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - pip-{{ checksum "requirements.txt" }}
      - run:
          command: pip install --user -r requirements.txt
          name: pip install
      - save_cache:
          key: pip-{{ checksum "requirements.txt" }}
          paths:
          - /home/circleci/.local/lib/
      - run:
          command: python -m pytest --junitxml=test-results/pytest/results.xml
          name: Test
      - store_test_results:
          path: test-results

workflows:
  main:
    jobs:
      - test-db
