version: 2.1

parameters:


jobs:
  test:
    docker:
      - image: circleci/python:latest
      - image: circleci/mongo:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - pip-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
          name: pip install
      - save_cache:
          key: pip-{{ checksum "requirements.txt" }}
          paths:
          - /home/circleci/.local/lib/
      - run:
          command: |
            . venv/bin/activate
            coverage run --source=inventory -m pytest --junitxml=test-results/pytest/results.xml
            coverage report
            coverage html
            coverage-badge -o coverage.svg
          name: Test
      - store_artifacts:
          path: htmlcov
      - store_artifacts:
          path: coverage.svg
      - store_test_results:
          path: test-results
  deploy:
    machine: 
      enabled: true
    steps:
      - run:
          name: Deploy over ssh
          command: ssh $SSH_USER@$SSH_HOST "cd inventory-v2/uwsgi-api-server/; git fetch; git reset --hard $CIRCLE_SHA1 ; sudo systemctl restart inventory-api"
workflows:
  main:
    jobs:
      - test
      - deploy:
          requires:
            - test
