version: 2.1

parameters:


jobs:
  test:
    docker:
      - image: circleci/python:latest
      - image: circleci/mongo:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - pip-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
          name: pip install
      - save_cache:
          key: pip-{{ checksum "requirements.txt" }}
          paths:
          - /home/circleci/.local/lib/
      - run:
          command: |
            . venv/bin/activate
            coverage run --source=inventory -m pytest --junitxml=test-results/pytest/results.xml
            coverage report
            coverage html
            coverage-badge -o coverage.svg
          name: Test
      - store_artifacts:
          path: htmlcov
      - store_artifacts:
          path: coverage.svg
      - store_test_results:
          path: test-results
  deploy:
    machine: 
      enabled: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup private key
        env:
          PRIVKEYENCRYPTED: ${{ secrets.DEPLOY_PRIVKEY_GPG_PASSWORD }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$PRIVKEYENCRYPTED" --output github_id_rsa github_id_rsa.gpg
          chmod 600 github_id_rsa
      - name: Deploy over ssh
        run: |
          ssh -T -i github_id_rsa -o UserKnownHostFile=known_hosts root@computemachines.com << EOF
           cd inventory/inventory-api/ 
           git pull
           echo $CIRCLE_SHA1 # test if substitution happens on ci server or production server
           sudo systemctl restart inventory-api
workflows:
  main:
    jobs:
      - test
      - deploy:
          requires:
            - test
