#! /usr/bin/sh

systemctl stop inventorius-api.service
systemctl stop inventorius-api.socket
systemctl disable inventorius-api.socket
systemctl disable inventorius-api.service

userdel www-uwsgi-inventorius-api

rm -v /etc/uwsgi/apps-enabled/pkg_inventorius-api.ini