#! /usr/bin/sh

echo "Running postinst script"

useradd -M www-uwsgi-inventorius-api

touch /etc/inventorius/secrets.ini

systemctl daemon-reload
systemctl enable inventorius-api.socket
systemctl enable inventorius-api.service
systemctl start inventorius-api.socket
systemctl start inventorius-api.service
