name: Test-Lint-Deploy

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: 3.8 #[3.6, 3.7, 3.8, 3.9, '3.x']
        mongodb-version: 3.6.8 #[4.0, 4.2, 4.4]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up monogdb
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
      - name: Run Tests
        run: pytest

  coverage-lint-reports:
    name: Coverage Linting
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up monogdb
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 3.6.8

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: tests with coverage
        run: coverage run --source=inventory -m pytest --junitxml=test-results/pytest/results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test results
          path: test-results/
        if: ${{ always() }}

      - name: Coverage Report
        run: |
          coverage report
          COVERAGE=`coverage report | grep "^TOTAL" | awk '{print $4}'`
          echo $COVERAGE
          echo coverageText="$COVERAGE" >> $GITHUB_ENV

      - name: Update Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: c6358499cfa820bcffe8535e6cabd586
          filename: coverage-inventory-v2-api-badge.json
          label: coverage
          message: ${{ env.coverageText }}
          color: orange
          cacheSeconds: 300
  deploy:
    name: Deploy to production
    runs-on: ubuntu-20.04
    needs: test
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup private key
        env:
          PRIVKEYENCRYPTED: ${{ secrets.DEPLOY_PRIVKEY_GPG_PASSWORD }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$PRIVKEYENCRYPTED" --output github_id_rsa github_id_rsa.gpg
          chmod 600 github_id_rsa
      - name: Run deployment commands on production server
        run: |
          ssh -i github_id_rsa -o UserKnownHostsFile=known_hosts root@computemachines.com \
            "cd inventory-v2/uwsgi-api-server/; git fetch; git reset --hard $GITHUB_SHA ; sudo systemctl restart inventory-api"