name: Coverage

on: push

jobs:
  test-coverage:
    name: Run pytest with coverage
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: ['3.x'] #[3.6, 3.7, 3.8, 3.9, '3.x']
        mongodb-version: [4.4] #[4.0, 4.2, 4.4]

    env:
      coverageColor: RED
      coverageLabel: test
      coverageText: FAIL

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up monogdb
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: coverage run --source=inventory -m pytest --junitxml=test-results/pytest/results.xml
      - name: Coverage Report
        run: |
          coverage report
          COVERAGE=`coverage report | grep "^TOTAL" | awk '{print $4}'`
          echo $COVERAGE
          echo coverageLabel=coverage >> $GITHUB_ENV
          echo coverageText="$COVERAGE" >> $GITHUB_ENV
          echo coverageColor=orange >> $GITHUB_ENV
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test results
          path: test-results/
        if: ${{ always() }}
      - name: Update Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: c6358499cfa820bcffe8535e6cabd586
          filename: coverage-inventory-v2-api-badge.json
          label: ${{ env.coverageLabel }}
          message: ${{ env.coverageText }}
          color: ${{ env.coverageColor }}
          cacheSeconds: 300